#!/bin/bash
#

# Aperture.defaults v1.0.0
# This script sets defaults for Aperture.
# www.brianspeir.com
#
# Copyright (C) 2013 Brian Speir. All rights reserved.
#
# Licensed under The BSD 3-Clause License. You may not use this file except
# in compliance with the License. You may obtain a copy of the License at
# http://opensource.org/licenses/BSD-3-Clause


# General ------------------------------------------------------------------ #

# Do not show last 12 months album.
defaults write com.apple.Aperture ShowLastNMonthsAlbum -bool NO

# Automatically stack new versions.
defaults write com.apple.Aperture StackNewVersions -bool YES

# Appearance --------------------------------------------------------------- #

# Do not badge referenced items.
defaults write com.apple.Aperture showReferenceBadge -bool NO

# Import ------------------------------------------------------------------- #

# Default import location is selected item.
defaults write com.apple.Aperture RKImportDefaultVersionDestinationType -int 1

# Export ------------------------------------------------------------------- #

# Email photo export preset:
defaults write com.apple.Aperture mailExportPresetName -string "Email Medium - JPEG"

# Web copyright:
defaults write com.apple.Aperture webCopyright -string "Copyright © 2013 Brian Speir. All rights reserved."

# Do not include location info in exported photos.
defaults write com.apple.Aperture includeGPSInImageExport -bool NO

# Do not include face info in exported photos.
defaults write com.apple.Aperture IncludeFaceNamesInImageExport -bool NO

# Previews ----------------------------------------------------------------- #

# Photo preview fit within 2880 x2880
defaults write com.apple.Aperture limitPreviewSubsample -int 2880

# Advanced ----------------------------------------------------------------- #

# Create new versions when making adjustments.
# defaults write com.apple.Aperture CreateNewVersionsWhenAdjusting -bool YES

# Other -------------------------------------------------------------------- #

# Allow Aperture to assign locations to photos that include GPS data.
defaults write com.apple.Aperture RKPlacesShouldReverseGeoTag -int 1

# Start full screen on launch.
# defaults write com.apple.Aperture StartFullscreenOnRelaunch -bool YES

# Disable registration information.
defaults -currentHost write $HOME/Library/Containers/com.apple.Aperture/Data/Library/Preferences/ByHost/com.apple.RegAperture AECoreTechNotSentCount -int 100
defaults -currentHost write $HOME/Library/Containers/com.apple.Aperture/Data/Library/Preferences/ByHost/com.apple.RegAperture AECoreTechDisplayedRegPanelCount -int 100
defaults -currentHost write $HOME/Library/Containers/com.apple.Aperture/Data/Library/Preferences/ByHost/com.apple.RegAperture AECoreTechRegister -string "YES"

# Disable welcome screen.
defaults write com.apple.Aperture didShow33WelcomeScreen -bool YES

# Presets ------------------------------------------------------------------ #

mkdir -p "$HOME/Library/Application Support/Aperture"

# Export Presets. Removed metadata export. Added 2048 x 2048 and Social.
cat > "$HOME/Library/Application Support/Aperture/Export Presets.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>2</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>JPEG - Original Size</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>1</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>JPEG - 50% of Original Size</string>
        <key>PercentToSizeBy</key>
        <real>50</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>2048</integer>
        <key>DestinationPixelWidth</key>
        <integer>2048</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>JPEG - Fit within 2048 x 2048</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>1024</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>JPEG - Fit within 1024 x 1024</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>640</integer>
        <key>DestinationPixelWidth</key>
        <integer>640</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>JPEG - Fit within 640 x 640</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>2</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>3</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>TIFF - Original Size (16-bit)</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>2</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>2</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>TIFF - Original Size (8-bit)</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>1</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>3</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>TIFF - 50% of Original Size</string>
        <key>PercentToSizeBy</key>
        <real>50</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>1024</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>3</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>TIFF - Fit within 1024 x 1024</string>
        <key>PercentToSizeBy</key>
        <real>50</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>2</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>1</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>PNG - Original Size</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>1</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>1</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>PNG - 50% of Original Size</string>
        <key>PercentToSizeBy</key>
        <real>50</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>1024</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>1</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>PNG - Fit within 1024 x 1024</string>
        <key>PercentToSizeBy</key>
        <real>50</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>640</integer>
        <key>DestinationPixelWidth</key>
        <integer>640</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>1</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>PNG - Fit within 640 x 640</string>
        <key>PercentToSizeBy</key>
        <real>50</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>2</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>4</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>PSD - Original Size (16-bit)</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>1</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>4</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>PSD - 50% of Original Size (16-bit)</string>
        <key>PercentToSizeBy</key>
        <real>50</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>640</integer>
        <key>DestinationPixelWidth</key>
        <integer>640</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>6</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Email Small - JPEG</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>1024</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>8</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Email Medium - JPEG</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>2</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Email Original Size - JPEG</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>500</integer>
        <key>DestinationPixelWidth</key>
        <integer>500</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>10</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Social Small - JPEG</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>5</integer>
            </dict>
        </dict>
    </dict>
</array>
</plist>
EOF

# File Folder Presets.
cat > "$HOME/Library/Application Support/Aperture/FileFolderPresets.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>plist</key>
    <array>
        <dict>
            <key>FormatString</key>
            <string>%y/%m/%a</string>
            <key>Name</key>
            <string>Year / Month / Day</string>
            <key>StartingCounterNumber</key>
            <integer>1</integer>
        </dict>
    </array>
    <key>version</key>
    <integer>2</integer>
</dict>
</plist>
EOF

# File Naming Presets.
cat > "$HOME/Library/Application Support/Aperture/FileNamingPresets.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>plist</key>
    <array>
        <dict>
            <key>FormatString</key>
            <string>%d at %t (%c) by %u</string>
            <key>Name</key>
            <string>Standard Name</string>
            <key>StartingCounterNumber</key>
            <integer>1</integer>
        </dict>
        <dict>
            <key>FormatString</key>
            <string>%y%m%a-%t-brianspeir</string>
            <key>Name</key>
            <string>Export Name</string>
            <key>StartingCounterNumber</key>
            <integer>1</integer>
        </dict>
        <dict>
            <key>FormatString</key>
            <string>%n</string>
            <key>Name</key>
            <string>Version Name</string>
            <key>StartingCounterNumber</key>
            <integer>1</integer>
        </dict>
    </array>
    <key>version</key>
    <integer>2</integer>
</dict>
</plist>
EOF

# Web Export Presets. Removed metadata export.
cat > "$HOME/Library/Application Support/Aperture/Web Export Presets.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>250</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>12</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Web Thumbnails - JPEG - Best Quality</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>1</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>250</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>8</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Web Thumbnails - JPEG - High Quality</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>1</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>250</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>5</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Web Thumbnails - JPEG - Medium Quality</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>1</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>12</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Web Detail - JPEG - Best Quality</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>1</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>8</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Web Detail - JPEG - High Quality</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>1</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>0</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>5</integer>
        <key>IncludeMetadata</key>
        <false/>
        <key>Name</key>
        <string>Web Detail - JPEG - Medium Quality</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>1</integer>
            </dict>
        </dict>
    </dict>
    <dict>
        <key>BlackPointCompensation</key>
        <false/>
        <key>ColorSyncProfile</key>
        <data>
        HT/aLttKiatgojxffH2B3Q==
        </data>
        <key>ColorSyncProfileName</key>
        <string>sRGB IEC61966-2.1</string>
        <key>DestinationDPI</key>
        <integer>72</integer>
        <key>DestinationPhysicalHeight</key>
        <real>4</real>
        <key>DestinationPhysicalHeightInCentimeters</key>
        <real>10</real>
        <key>DestinationPhysicalWidth</key>
        <real>6</real>
        <key>DestinationPhysicalWidthInCentimeters</key>
        <real>15</real>
        <key>DestinationPixelHeight</key>
        <integer>768</integer>
        <key>DestinationPixelWidth</key>
        <integer>1024</integer>
        <key>ExportSizeStyle</key>
        <integer>0</integer>
        <key>FileSizeLimitInKilobytes</key>
        <integer>500</integer>
        <key>GammaSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGGammaOperation</string>
            <key>DGOperationDisplayName</key>
            <string>Gamma</string>
            <key>DGOperationIdentifier</key>
            <string>DGGammaOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <true/>
            <key>inputKeys</key>
            <dict>
                <key>inputPower</key>
                <real>1</real>
            </dict>
        </dict>
        <key>ImageFormat</key>
        <integer>1</integer>
        <key>ImageQualityType</key>
        <integer>0</integer>
        <key>ImageQualityValue</key>
        <integer>8</integer>
        <key>IncludeMetadata</key>
        <true/>
        <key>Name</key>
        <string>Web - PNG</string>
        <key>PercentToSizeBy</key>
        <real>100</real>
        <key>ScaleWatermark</key>
        <false/>
        <key>WatermarkSettings</key>
        <dict>
            <key>DGOperationClassName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationDisplayName</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationIdentifier</key>
            <string>DGImageCompositeScaledOperation</string>
            <key>DGOperationVersionNumber</key>
            <integer>0</integer>
            <key>enabled</key>
            <false/>
            <key>inputKeys</key>
            <dict>
                <key>inputOpacity</key>
                <real>0.5</real>
                <key>inputRectPointLocation</key>
                <integer>1</integer>
            </dict>
        </dict>
    </dict>
</array>
</plist>
EOF
